import streamlit as st
import pandas as pd
from datetime import datetime
from fpdf import FPDF
import sys
import os
from pathlib import Path

SCRIPT_DIR = os.path.dirname(os.path.realpath(__file__))
sys.path.append(os.path.dirname(SCRIPT_DIR))


from corefunc.db import supabase_client

# This is the path to the directory containing this file (config directory)
CURRENT_DIR = Path(__file__).resolve().parent

# The project root is one level up from the config directory
ROOT_DIR = CURRENT_DIR.parent
print("my root dir is", ROOT_DIR)
print ("Font file exists:", os.path.join(ROOT_DIR,'static','fonts/DejaVuSans.ttf'))

class PDF(FPDF):
    def __init__(self):
        super().__init__()
        self.font_added = False

    def header(self):
        if not self.font_added:
            self.add_font('DejaVuSans', '', os.path.join(ROOT_DIR,'static','fonts/DejaVuSans.ttf'))
            self.font_added = True
        self.set_font("DejaVuSans", size=14)
        self.cell(0, 15, "PUBLIC PARTICIPATION SYNTHESIS REPORT", new_x="LMARGIN", new_y="NEXT", align="C")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        #self.set_font("DejaVuSans", size=9)
        self.set_font("DejaVuSans", size=9)
        page_text = f"Page {self.page_no()} • Generated by CivicSense AI on {datetime.now().strftime('%d %B %Y')}"
        self.cell(0, 10, page_text, align="C")

st.title("📊 Public Participation Synthesis Report")
st.markdown("Professional report ready for the Clerk of the National Assembly — generated in seconds.")

# Load bills
bills_result = supabase_client.table("bills").select("id,title").order("published_at", desc=True).execute()
bills = bills_result.data

if not bills:
    st.warning("No bills in the database yet. Run the scraper first.")
    st.stop()

bill_titles = [b["title"] for b in bills]
selected_title = st.selectbox("Select bill for report", bill_titles)
bill_id = next(b["id"] for b in bills if b["title"] == selected_title)

if st.button("Generate Official Report →", type="primary", use_container_width=True):
    feedbacks_result = supabase_client.table("feedback").select("*").eq("bill_id", bill_id).execute()
    feedbacks = feedbacks_result.data

    if not feedbacks:
        st.warning("No public feedback submitted for this bill yet.")
        st.stop()

    df = pd.DataFrame(feedbacks)
    total = len(df)
    support = len(df[df.stance == "Support"])
    oppose = len(df[df.stance == "Oppose"])
    neutral = len(df[df.stance == "Neutral"])

    # Build clean comment block for AI
    comments = ""
    for f in feedbacks:
        if f["comment"]:
            county = f.get("county") or "Kenya"
            comments += f"• {f['stance']} ({county}): {f['comment'].strip()}\n"
        if f.get("suggested_amendment"):
            comments += f"   ↳ Suggestion: {f['suggested_amendment'].strip()}\n"

    # AI Executive Summary
    with st.spinner("AI drafting executive summary..."):
        try:
            from core.llm import llm
            prompt = f"""
You are the Clerk of the National Assembly preparing the official Article 118 public participation report.

Bill: {selected_title}

Participation Statistics:
• Total submissions: {total}
• Support: {support} ({support/total*100:.1f}%)
• Oppose: {oppose} ({oppose/total*100:.1f}%)
• Neutral: {neutral} ({neutral/total*100:.1f}%)

Citizen voices:
{comments}

Write a neutral, formal executive summary (250–350 words) in parliamentary language, followed by the top 5 most common concerns or suggested amendments as numbered points.
"""
            response = llm.invoke(prompt)
            ai_summary = response.content.strip()
        except Exception as e:
            st.error("AI summary failed — using basic version.")
            ai_summary = f"{total} submissions received ({support} support, {oppose} oppose, {neutral} neutral). Full feedback attached below."

    # Generate PDF with full Unicode support
    pdf = PDF()
    pdf.add_page()
    pdf.set_font("DejaVuSans", size=12)

    # Title & date
    #pdf.set_font("DejaVu", "B", 18)
    pdf.set_font("DejaVuSans", size=18)
    pdf.cell(0, 15, selected_title, new_x="LMARGIN", new_y="NEXT", align="C")
    #pdf.set_font("DejaVu", size=11)
    pdf.set_font("DejaVuSans", size=11)
    pdf.cell(0, 8, f"Public Participation Synthesis Report — {datetime.now().strftime('%d %B %Y')}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(10)

    # Stats line
    #pdf.set_font("DejaVu", "B", 12)
    pdf.set_font("DejaVuSans", size=12)
    pdf.cell(0, 10, f"Total Submissions: {total}  •  Support: {support}  •  Oppose: {oppose}  •  Neutral: {neutral}",
              new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)

    # Executive Summary
    #pdf.set_font("DejaVu", "B", 14)
    pdf.set_font("DejaVuSans", size=14)
    pdf.cell(0, 10, "Executive Summary", new_x="LMARGIN", new_y="NEXT")
    #pdf.set_font("DejaVu", "", 11)
    pdf.set_font("DejaVuSans", size=11)
    pdf.multi_cell(0, 8, ai_summary)
    pdf.ln(8)

    # Full submissions
    pdf.add_page()
    #pdf.set_font("DejaVu", "B", 13)
    pdf.set_font("DejaVuSans", size=13)
    pdf.cell(0, 10, "Full Citizen Submissions", new_x="LMARGIN", new_y="NEXT")
    #pdf.set_font("DejaVu", "", 10)
    pdf.set_font("DejaVuSans", size=10)
    for i, f in enumerate(feedbacks, 1):
        county = f.get("county") or "Kenya"
        line = f"{i}. [{f['stance']}] {f.get('comment','')} {f.get('suggested_amendment','')} — {county}"
        pdf.multi_cell(0, 6, line.strip())

    # Output
    pdf_bytes = bytes(pdf.output(dest='S'))

    st.success("Report generated perfectly!")
    st.download_button(
        label="⬇️ Download Official PDF Report — Ready for Parliament",
        data=pdf_bytes,
        file_name=f"CivicSense_Report_{selected_title[:40].replace(' ', '_')}_{datetime.now().strftime('%Y%m%d')}.pdf",
        mime="application/pdf",
        use_container_width=True
    )

    with st.expander("Preview AI Executive Summary"):
        st.write(ai_summary)